"""
Based on https://nethackwiki.com/wiki/Armor
This glossary only roughly describes the properties of the armor.
There is some behavior unimplemented within this dictionary, such as randomised appearance and so force.
https://nethackwiki.com/wiki/Randomized_appearance
"""

ARMOR_GLOSSARY = {
    1977: {'name': 'leather hat',
           'cost': 8,
           'weight': 3,
           'AC': 1,
           'max_AC': 8,
           'material': 'leather',
           'effect': '',
           'MC': '',
           'probability': '6',
           'magical': False,
           'armor_type': 'helms'},
    1978: {'name': 'iron skull cap',
           'cost': 10,
           'weight': 30,
           'AC': 1,
           'max_AC': 6,
           'material': 'iron',
           'effect': '',
           'MC': '',
           'probability': '6',
           'magical': False,
           'armor_type': 'helms'},
    1979: {'name': 'hard hat',
           'cost': 20,
           'weight': 40,
           'AC': 2,
           'max_AC': 7,
           'material': 'iron',
           'effect': '',
           'MC': '',
           'probability': '6',
           'magical': False,
           'armor_type': 'helms'},
    1980: {'name': 'fedora',
           'cost': 1,
           'weight': 3,
           'AC': 0,
           'max_AC': 5,
           'material': 'cloth',
           'effect': '',
           'MC': '',
           'probability': '--',
           'magical': False,
           'armor_type': 'helms'},
    1981: {'name': 'conical hat',
           'cost': 1,
           'weight': 4,
           'AC': 0,
           'max_AC': 5,
           'material': 'cloth',
           'effect': 'Stupid',
           'MC': '',
           'probability': '3',
           'magical': True,
           'armor_type': 'helms'},
    1982: {'name': 'conical hat',
           'cost': 1,
           'weight': 4,
           'AC': 0,
           'max_AC': 5,
           'material': 'cloth',
           'effect': 'Stupid',
           'MC': '',
           'probability': '3',
           'magical': True,
           'armor_type': 'helms'},
    1983: {'name': 'dented pot',
           'cost': 8,
           'weight': 10,
           'AC': 1,
           'max_AC': 6,
           'material': 'iron',
           'effect': '',
           'MC': '',
           'probability': '2',
           'magical': False,
           'armor_type': 'helms'},
    1984: {'name': 'plumed helmet',
           'cost': 10,
           'weight': 30,
           'AC': 1,
           'max_AC': 6,
           'material': 'iron',
           'effect': '',
           'MC': '',
           'probability': '10',
           'magical': False,
           'armor_type': 'helms'},
    1985: {'name': 'etched helmet',
           'cost': 50,
           'weight': 50,
           'AC': 1,
           'max_AC': 6,
           'material': 'iron',
           'effect': 'Int+Wis',
           'MC': '',
           'probability': '6',
           'magical': True,
           'armor_type': 'helms'},
    1986: {'name': 'crested helmet',
           'cost': 50,
           'weight': 50,
           'AC': 1,
           'max_AC': 6,
           'material': 'iron',
           'effect': 'Align',
           'MC': '',
           'probability': '6',
           'magical': True,
           'armor_type': 'helms'},
    1987: {'name': 'visored helmet',
           'cost': 50,
           'weight': 50,
           'AC': 1,
           'max_AC': 6,
           'material': 'iron',
           'effect': 'ESP',
           'MC': '',
           'probability': '2',
           'magical': True,
           'armor_type': 'helms'},
    1988: {'name': 'gray dragon scale mail',
           'cost': 900,
           'weight': 40,
           'AC': 9,
           'max_AC': 14,
           'material': 'dragon',
           'effect': 'Resist%',
           'MC': '',
           'probability': '--',
           'magical': True,
           'armor_type': 'dragon suits'},
    1989: {'name': 'silver dragon scale mail',
           'cost': 900,
           'weight': 40,
           'AC': 9,
           'max_AC': 14,
           'material': 'dragon',
           'effect': 'Resist%',
           'MC': '',
           'probability': '--',
           'magical': True,
           'armor_type': 'dragon suits'},
    1990: {'name': 'red dragon scale mail',
           'cost': 900,
           'weight': 40,
           'AC': 9,
           'max_AC': 14,
           'material': 'dragon',
           'effect': 'Resist%',
           'MC': '',
           'probability': '--',
           'magical': True,
           'armor_type': 'dragon suits'},
    1991: {'name': 'white dragon scale mail',
           'cost': 900,
           'weight': 40,
           'AC': 9,
           'max_AC': 14,
           'material': 'dragon',
           'effect': 'Resist%',
           'MC': '',
           'probability': '--',
           'magical': True,
           'armor_type': 'dragon suits'},
    1992: {'name': 'orange dragon scale mail',
           'cost': 900,
           'weight': 40,
           'AC': 9,
           'max_AC': 14,
           'material': 'dragon',
           'effect': 'Resist%',
           'MC': '',
           'probability': '--',
           'magical': True,
           'armor_type': 'dragon suits'},
    1993: {'name': 'black dragon scale mail',
           'cost': 900,
           'weight': 40,
           'AC': 9,
           'max_AC': 14,
           'material': 'dragon',
           'effect': 'Resist%',
           'MC': '',
           'probability': '--',
           'magical': True,
           'armor_type': 'dragon suits'},
    1994: {'name': 'blue dragon scale mail',
           'cost': 900,
           'weight': 40,
           'AC': 9,
           'max_AC': 14,
           'material': 'dragon',
           'effect': 'Resist%',
           'MC': '',
           'probability': '--',
           'magical': True,
           'armor_type': 'dragon suits'},
    1995: {'name': 'green dragon scale mail',
           'cost': 900,
           'weight': 40,
           'AC': 9,
           'max_AC': 14,
           'material': 'dragon',
           'effect': 'Resist%',
           'MC': '',
           'probability': '--',
           'magical': True,
           'armor_type': 'dragon suits'},
    1996: {'name': 'yellow dragon scale mail',
           'cost': 900,
           'weight': 40,
           'AC': 9,
           'max_AC': 14,
           'material': 'dragon',
           'effect': 'Resist%',
           'MC': '',
           'probability': '--',
           'magical': True,
           'armor_type': 'dragon suits'},
    1997: {'name': 'gray dragon scales',
           'cost': 500,
           'weight': 40,
           'AC': 3,
           'max_AC': 8,
           'material': 'dragon',
           'effect': 'Resist%',
           'MC': '',
           'probability': '--',
           'magical': False,
           'armor_type': 'dragon suits'},
    1998: {'name': 'silver dragon scales',
           'cost': 500,
           'weight': 40,
           'AC': 3,
           'max_AC': 8,
           'material': 'dragon',
           'effect': 'Resist%',
           'MC': '',
           'probability': '--',
           'magical': False,
           'armor_type': 'dragon suits'},
    1999: {'name': 'red dragon scales',
           'cost': 500,
           'weight': 40,
           'AC': 3,
           'max_AC': 8,
           'material': 'dragon',
           'effect': 'Resist%',
           'MC': '',
           'probability': '--',
           'magical': False,
           'armor_type': 'dragon suits'},
    2000: {'name': 'white dragon scales',
           'cost': 500,
           'weight': 40,
           'AC': 3,
           'max_AC': 8,
           'material': 'dragon',
           'effect': 'Resist%',
           'MC': '',
           'probability': '--',
           'magical': False,
           'armor_type': 'dragon suits'},
    2001: {'name': 'orange dragon scales',
           'cost': 500,
           'weight': 40,
           'AC': 3,
           'max_AC': 8,
           'material': 'dragon',
           'effect': 'Resist%',
           'MC': '',
           'probability': '--',
           'magical': False,
           'armor_type': 'dragon suits'},
    2002: {'name': 'black dragon scales',
           'cost': 500,
           'weight': 40,
           'AC': 3,
           'max_AC': 8,
           'material': 'dragon',
           'effect': 'Resist%',
           'MC': '',
           'probability': '--',
           'magical': False,
           'armor_type': 'dragon suits'},
    2003: {'name': 'blue dragon scales',
           'cost': 500,
           'weight': 40,
           'AC': 3,
           'max_AC': 8,
           'material': 'dragon',
           'effect': 'Resist%',
           'MC': '',
           'probability': '--',
           'magical': False,
           'armor_type': 'dragon suits'},
    2004: {'name': 'green dragon scales',
           'cost': 500,
           'weight': 40,
           'AC': 3,
           'max_AC': 8,
           'material': 'dragon',
           'effect': 'Resist%',
           'MC': '',
           'probability': '--',
           'magical': False,
           'armor_type': 'dragon suits'},
    2005: {'name': 'yellow dragon scales',
           'cost': 500,
           'weight': 40,
           'AC': 3,
           'max_AC': 8,
           'material': 'dragon',
           'effect': 'Resist%',
           'MC': '',
           'probability': '--',
           'magical': False,
           'armor_type': 'dragon suits'},
    2006: {'name': 'plate mail',
           'cost': 600,
           'weight': 450,
           'AC': 7,
           'max_AC': 12,
           'material': 'iron',
           'effect': '',
           'MC': '2',
           'probability': '44',
           'magical': False,
           'armor_type': 'suits'},
    2007: {'name': 'crystal plate mail',
           'cost': 820,
           'weight': 450,
           'AC': 7,
           'max_AC': 12,
           'material': 'glass',
           'effect': '',
           'MC': '2',
           'probability': '10',
           'magical': False,
           'armor_type': 'suits'},
    2008: {'name': 'bronze plate mail',
           'cost': 400,
           'weight': 450,
           'AC': 6,
           'max_AC': 11,
           'material': 'copper',
           'effect': '',
           'MC': '1',
           'probability': '25',
           'magical': False,
           'armor_type': 'suits'},
    2009: {'name': 'splint mail',
           'cost': 80,
           'weight': 400,
           'AC': 6,
           'max_AC': 11,
           'material': 'iron',
           'effect': '',
           'MC': '1',
           'probability': '62',
           'magical': False,
           'armor_type': 'suits'},
    2010: {'name': 'banded mail',
           'cost': 90,
           'weight': 350,
           'AC': 6,
           'max_AC': 11,
           'material': 'iron',
           'effect': '',
           'MC': '1',
           'probability': '72',
           'magical': False,
           'armor_type': 'suits'},
    2011: {'name': 'dwarvish mithril-coat',
           'cost': 240,
           'weight': 150,
           'AC': 6,
           'max_AC': 11,
           'material': 'mithril',
           'effect': '',
           'MC': '2',
           'probability': '10',
           'magical': False,
           'armor_type': 'suits'},
    2012: {'name': 'elven mithril-coat',
           'cost': 240,
           'weight': 150,
           'AC': 5,
           'max_AC': 12,
           'material': 'mithril',
           'effect': '',
           'MC': '2',
           'probability': '15',
           'magical': False,
           'armor_type': 'suits'},
    2013: {'name': 'chain mail',
           'cost': 75,
           'weight': 300,
           'AC': 5,
           'max_AC': 10,
           'material': 'iron',
           'effect': '',
           'MC': '1',
           'probability': '72',
           'magical': False,
           'armor_type': 'suits'},
    2014: {'name': 'crude chain mail',
           'cost': 75,
           'weight': 300,
           'AC': 4,
           'max_AC': 9,
           'material': 'iron',
           'effect': '',
           'MC': '1',
           'probability': '20',
           'magical': False,
           'armor_type': 'suits'},
    2015: {'name': 'scale mail',
           'cost': 45,
           'weight': 250,
           'AC': 4,
           'max_AC': 9,
           'material': 'iron',
           'effect': '',
           'MC': '1',
           'probability': '72',
           'magical': False,
           'armor_type': 'suits'},
    2016: {'name': 'studded leather armor',
           'cost': 15,
           'weight': 200,
           'AC': 3,
           'max_AC': 8,
           'material': 'leather',
           'effect': '',
           'MC': '1',
           'probability': '72',
           'magical': False,
           'armor_type': 'suits'},
    2017: {'name': 'ring mail',
           'cost': 100,
           'weight': 250,
           'AC': 3,
           'max_AC': 8,
           'material': 'iron',
           'effect': '',
           'MC': '1',
           'probability': '72',
           'magical': False,
           'armor_type': 'suits'},
    2018: {'name': 'crude ring mail',
           'cost': 80,
           'weight': 250,
           'AC': 2,
           'max_AC': 7,
           'material': 'iron',
           'effect': '',
           'MC': '1',
           'probability': '20',
           'magical': False,
           'armor_type': 'suits'},
    2019: {'name': 'leather armor',
           'cost': 5,
           'weight': 150,
           'AC': 2,
           'max_AC': 7,
           'material': 'leather',
           'effect': '',
           'MC': '1',
           'probability': '82',
           'magical': False,
           'armor_type': 'suits'},
    2020: {'name': 'leather jacket',
           'cost': 10,
           'weight': 30,
           'AC': 1,
           'max_AC': 6,
           'material': 'leather',
           'effect': '',
           'MC': '',
           'probability': '12',
           'magical': False,
           'armor_type': 'suits'},
    2021: {'name': 'Hawaiian shirt',
           'cost': 3,
           'weight': 5,
           'AC': 0,
           'max_AC': 5,
           'material': 'cloth',
           'effect': 'Shop',
           'MC': '',
           'probability': '8',
           'magical': False,
           'armor_type': 'shirts'},
    2022: {'name': 'T-shirt',
           'cost': 2,
           'weight': 5,
           'AC': 0,
           'max_AC': 5,
           'material': 'cloth',
           'effect': 'Shop',
           'MC': '',
           'probability': '2',
           'magical': False,
           'armor_type': 'shirts'},
    2023: {'name': 'mummy wrapping',
           'cost': 2,
           'weight': 3,
           'AC': 0,
           'max_AC': 5,
           'material': 'cloth',
           'effect': 'Vis',
           'MC': '1',
           'probability': '--',
           'magical': False,
           'armor_type': 'cloaks'},
    2024: {'name': 'faded pall',
           'cost': 60,
           'weight': 10,
           'AC': 1,
           'max_AC': 8,
           'material': 'cloth',
           'effect': 'Stealth',
           'MC': '1',
           'probability': '8',
           'magical': True,
           'armor_type': 'cloaks'},
    2025: {'name': 'coarse mantelet',
           'cost': 40,
           'weight': 10,
           'AC': 0,
           'max_AC': 5,
           'material': 'cloth',
           'effect': '',
           'MC': '1',
           'probability': '8',
           'magical': False,
           'armor_type': 'cloaks'},
    2026: {'name': 'hooded cloak',
           'cost': 50,
           'weight': 10,
           'AC': 0,
           'max_AC': 5,
           'material': 'cloth',
           'effect': '',
           'MC': '1',
           'probability': '8',
           'magical': False,
           'armor_type': 'cloaks'},
    2027: {'name': 'slippery cloak',
           'cost': 50,
           'weight': 10,
           'AC': 1,
           'max_AC': 6,
           'material': 'cloth',
           'effect': 'Water',
           'MC': '2',
           'probability': '8',
           'magical': False,
           'armor_type': 'cloaks'},
    2028: {'name': 'robe',
           'cost': 50,
           'weight': 15,
           'AC': 2,
           'max_AC': 7,
           'material': 'cloth',
           'effect': 'Spell1',
           'MC': '2',
           'probability': '3',
           'magical': True,
           'armor_type': 'cloaks'},
    2029: {'name': 'apron',
           'cost': 50,
           'weight': 10,
           'AC': 1,
           'max_AC': 6,
           'material': 'cloth',
           'effect': 'Poi+Acd',
           'MC': '1',
           'probability': '9',
           'magical': True,
           'armor_type': 'cloaks'},
    2030: {'name': 'leather cloak',
           'cost': 40,
           'weight': 15,
           'AC': 1,
           'max_AC': 6,
           'material': 'leather',
           'effect': '',
           'MC': '1',
           'probability': '8',
           'magical': False,
           'armor_type': 'cloaks'},
    2031: {'name': 'tattered cape',
           'cost': 50,
           'weight': 10,
           'AC': 3,
           'max_AC': 8,
           'material': 'cloth',
           'effect': 'Prot',
           'MC': '3',
           'probability': '9',
           'magical': True,
           'armor_type': 'cloaks'},
    2032: {'name': 'opera cloak',
           'cost': 60,
           'weight': 10,
           'AC': 1,
           'max_AC': 6,
           'material': 'cloth',
           'effect': 'Invis',
           'MC': '1',
           'probability': '10',
           'magical': True,
           'armor_type': 'cloaks'},
    2033: {'name': 'ornamental cope',
           'cost': 60,
           'weight': 10,
           'AC': 1,
           'max_AC': 6,
           'material': 'cloth',
           'effect': 'Magic',
           'MC': '1',
           'probability': '2',
           'magical': True,
           'armor_type': 'cloaks'},
    2034: {'name': 'piece of cloth',
           'cost': 50,
           'weight': 10,
           'AC': 1,
           'max_AC': 6,
           'material': 'cloth',
           'effect': 'Displ',
           'MC': '1',
           'probability': '10',
           'magical': True,
           'armor_type': 'cloaks'},
    2035: {'name': 'small shield',
           'cost': 3,
           'weight': 30,
           'AC': 1,
           'max_AC': 6,
           'material': 'wood',
           'effect': 'Spell2',
           'MC': '',
           'probability': '6',
           'magical': False,
           'armor_type': 'shields'},
    2036: {'name': 'blue and green shield',
           'cost': 7,
           'weight': 40,
           'AC': 2,
           'max_AC': 9,
           'material': 'wood',
           'effect': '',
           'MC': '',
           'probability': '2',
           'magical': False,
           'armor_type': 'shields'},
    2037: {'name': 'white-handed shield',
           'cost': 7,
           'weight': 50,
           'AC': 1,
           'max_AC': 6,
           'material': 'iron',
           'effect': '',
           'MC': '',
           'probability': '2',
           'magical': False,
           'armor_type': 'shields'},
    2038: {'name': 'red-eyed shield',
           'cost': 7,
           'weight': 50,
           'AC': 1,
           'max_AC': 6,
           'material': 'iron',
           'effect': '',
           'MC': '',
           'probability': '2',
           'magical': False,
           'armor_type': 'shields'},
    2039: {'name': 'large shield',
           'cost': 10,
           'weight': 100,
           'AC': 2,
           'max_AC': 7,
           'material': 'iron',
           'effect': '',
           'MC': '',
           'probability': '7',
           'magical': False,
           'armor_type': 'shields'},
    2040: {'name': 'large round shield',
           'cost': 10,
           'weight': 100,
           'AC': 2,
           'max_AC': 7,
           'material': 'iron',
           'effect': '',
           'MC': '',
           'probability': '4',
           'magical': False,
           'armor_type': 'shields'},
    2041: {'name': 'polished silver shield',
           'cost': 50,
           'weight': 50,
           'AC': 2,
           'max_AC': 7,
           'material': 'silver',
           'effect': 'Reflect',
           'MC': '',
           'probability': '3',
           'magical': True,
           'armor_type': 'shields'},
    2042: {'name': 'old gloves',
           'cost': 8,
           'weight': 10,
           'AC': 1,
           'max_AC': 6,
           'material': 'leather',
           'effect': '',
           'MC': '',
           'probability': '16',
           'magical': False,
           'armor_type': 'gloves'},
    2043: {'name': 'padded gloves',
           'cost': 50,
           'weight': 10,
           'AC': 1,
           'max_AC': 6,
           'material': 'leather',
           'effect': 'Dex',
           'MC': '',
           'probability': '8',
           'magical': True,
           'armor_type': 'gloves'},
    2044: {'name': 'riding gloves',
           'cost': 50,
           'weight': 10,
           'AC': 1,
           'max_AC': 6,
           'material': 'leather',
           'effect': 'Fumble',
           'MC': '',
           'probability': '8',
           'magical': True,
           'armor_type': 'gloves'},
    2045: {'name': 'fencing gloves',
           'cost': 50,
           'weight': 30,
           'AC': 1,
           'max_AC': 6,
           'material': 'iron',
           'effect': 'Str',
           'MC': '',
           'probability': '8',
           'magical': True,
           'armor_type': 'gloves'},
    2046: {'name': 'walking shoes',
           'cost': 8,
           'weight': 10,
           'AC': 1,
           'max_AC': 6,
           'material': 'leather',
           'effect': '',
           'MC': '',
           'probability': '25',
           'magical': False,
           'armor_type': 'boots'},
    2047: {'name': 'hard shoes',
           'cost': 16,
           'weight': 50,
           'AC': 2,
           'max_AC': 7,
           'material': 'iron',
           'effect': '',
           'MC': '',
           'probability': '7',
           'magical': False,
           'armor_type': 'boots'},
    2048: {'name': 'jackboots',
           'cost': 12,
           'weight': 20,
           'AC': 2,
           'max_AC': 7,
           'material': 'leather',
           'effect': '',
           'MC': '',
           'probability': '15',
           'magical': False,
           'armor_type': 'boots'},
    2049: {'name': 'combat boots',
           'cost': 50,
           'weight': 20,
           'AC': 1,
           'max_AC': 6,
           'material': 'leather',
           'effect': 'Speed',
           'MC': '',
           'probability': '12',
           'magical': True,
           'armor_type': 'boots'},
    2050: {'name': 'jungle boots',
           'cost': 50,
           'weight': 20,
           'AC': 1,
           'max_AC': 6,
           'material': 'leather',
           'effect': 'WWalk',
           'MC': '',
           'probability': '12',
           'magical': True,
           'armor_type': 'boots'},
    2051: {'name': 'hiking boots',
           'cost': 50,
           'weight': 20,
           'AC': 1,
           'max_AC': 6,
           'material': 'leather',
           'effect': 'Jump',
           'MC': '',
           'probability': '12',
           'magical': True,
           'armor_type': 'boots'},
    2052: {'name': 'mud boots',
           'cost': 8,
           'weight': 15,
           'AC': 1,
           'max_AC': 8,
           'material': 'leather',
           'effect': 'Stealth',
           'MC': '',
           'probability': '12',
           'magical': True,
           'armor_type': 'boots'},
    2053: {'name': 'buckled boots',
           'cost': 8,
           'weight': 50,
           'AC': 1,
           'max_AC': 6,
           'material': 'iron',
           'effect': 'Kick',
           'MC': '',
           'probability': '12',
           'magical': True,
           'armor_type': 'boots'},
    2054: {'name': 'riding boots',
           'cost': 30,
           'weight': 20,
           'AC': 1,
           'max_AC': 6,
           'material': 'leather',
           'effect': 'Fumble',
           'MC': '',
           'probability': '12',
           'magical': True,
           'armor_type': 'boots'},
    2055: {'name': 'snow boots',
           'cost': 30,
           'weight': 15,
           'AC': 1,
           'max_AC': 6,
           'material': 'leather',
           'effect': 'Lev',
           'MC': '',
           'probability': '12',
           'magical': True,
           'armor_type': 'boots'}
}
