"""
Based on https://nethackwiki.com/wiki/Weapon
This glossary only roughly describes the properties of the armor.
There is some behavior unimplemented within this dictionary
"""

WEAPON_GLOSSARY = {
    1907: {'name': 'arrow',
           'skill': 'bow',
           'cost': 2,
           'weight': 1,
           'probability': '55†',
           'damage_S': 'd6',
           'damage_L': 'd6',
           'material': 'iron'},
    1908: {'name': 'runed arrow',
           'skill': 'bow',
           'cost': 2,
           'weight': 1,
           'probability': '20†',
           'damage_S': 'd7',
           'damage_L': 'd6',
           'material': 'wood'},
    1909: {'name': 'crude arrow',
           'skill': 'bow',
           'cost': 2,
           'weight': 1,
           'probability': '20†',
           'damage_S': 'd5',
           'damage_L': 'd6',
           'material': 'iron'},
    1910: {'name': 'silver arrow',
           'skill': 'bow',
           'cost': 5,
           'weight': 1,
           'probability': '12',
           'damage_S': 'd6',
           'damage_L': 'd6',
           'material': 'silver'},
    1911: {'name': 'bamboo arrow',
           'skill': 'bow',
           'cost': 4,
           'weight': 1,
           'probability': '15',
           'damage_S': 'd7',
           'damage_L': 'd7',
           'material': 'metal'},
    1912: {'name': 'crossbow bolt',
           'skill': 'crossbow',
           'cost': 2,
           'weight': 1,
           'probability': '55†',
           'damage_S': 'd4+1',
           'damage_L': 'd6+1',
           'material': 'iron'},
    1913: {'name': 'dart',
           'skill': 'dart',
           'cost': 2,
           'weight': 1,
           'probability': '60†',
           'damage_S': 'd3',
           'damage_L': 'd2',
           'material': 'iron'},
    1914: {'name': 'throwing star',
           'skill': 'shuriken',
           'cost': 5,
           'weight': 1,
           'probability': '35',
           'damage_S': 'd8',
           'damage_L': 'd6',
           'material': 'iron'},
    1915: {'name': 'boomerang',
           'skill': 'boomerang',
           'cost': 20,
           'weight': 5,
           'probability': '15',
           'damage_S': 'd9',
           'damage_L': 'd9',
           'material': 'wood'},
    1916: {'name': 'spear',
           'skill': 'spear',
           'cost': 3,
           'weight': 30,
           'probability': '50†',
           'damage_S': 'd6',
           'damage_L': 'd8',
           'material': 'iron'},
    1917: {'name': 'runed spear',
           'skill': 'spear',
           'cost': 3,
           'weight': 30,
           'probability': '10†',
           'damage_S': 'd7',
           'damage_L': 'd8',
           'material': 'wood'},
    1918: {'name': 'crude spear',
           'skill': 'spear',
           'cost': 3,
           'weight': 30,
           'probability': '13†',
           'damage_S': 'd5',
           'damage_L': 'd8',
           'material': 'iron'},
    1919: {'name': 'stout spear',
           'skill': 'spear',
           'cost': 3,
           'weight': 35,
           'probability': '12†',
           'damage_S': 'd8',
           'damage_L': 'd8',
           'material': 'iron'},
    1920: {'name': 'silver spear',
           'skill': 'spear',
           'cost': 40,
           'weight': 36,
           'probability': '2',
           'damage_S': 'd6',
           'damage_L': 'd8',
           'material': 'silver'},
    1921: {'name': 'throwing spear',
           'skill': 'spear',
           'cost': 3,
           'weight': 20,
           'probability': '10',
           'damage_S': 'd6',
           'damage_L': 'd6',
           'material': 'iron'},
    1922: {'name': 'trident',
           'skill': 'trident',
           'cost': 5,
           'weight': 25,
           'probability': '8',
           'damage_S': 'd6+1',
           'damage_L': '3d4',
           'material': 'iron'},
    1923: {'name': 'dagger',
           'skill': 'dagger',
           'cost': 4,
           'weight': 10,
           'probability': '30',
           'damage_S': 'd4',
           'damage_L': 'd3',
           'material': 'iron'},
    1924: {'name': 'runed dagger',
           'skill': 'dagger',
           'cost': 4,
           'weight': 10,
           'probability': '10†',
           'damage_S': 'd5',
           'damage_L': 'd3',
           'material': 'wood'},
    1925: {'name': 'crude dagger',
           'skill': 'dagger',
           'cost': 4,
           'weight': 10,
           'probability': '12†',
           'damage_S': 'd3',
           'damage_L': 'd3',
           'material': 'iron'},
    1926: {'name': 'silver dagger',
           'skill': 'dagger',
           'cost': 40,
           'weight': 12,
           'probability': '3',
           'damage_S': 'd4',
           'damage_L': 'd3',
           'material': 'silver'},
    1927: {'name': 'athame',
           'skill': 'dagger',
           'cost': 4,
           'weight': 10,
           'probability': 'N/A',
           'damage_S': 'd4',
           'damage_L': 'd3',
           'material': 'iron'},
    1928: {'name': 'scalpel',
           'skill': 'knife',
           'cost': 4,
           'weight': 5,
           'probability': 'N/A',
           'damage_S': 'd3',
           'damage_L': 'd3',
           'material': 'metal'},
    1929: {'name': 'knife',
           'skill': 'knife',
           'cost': 4,
           'weight': 5,
           'probability': '20',
           'damage_S': 'd3',
           'damage_L': 'd2',
           'material': 'iron'},
    1930: {'name': 'stiletto',
           'skill': 'knife',
           'cost': 4,
           'weight': 5,
           'probability': '5',
           'damage_S': 'd3',
           'damage_L': 'd2',
           'material': 'iron'},
    1931: {'name': 'worm tooth',
           'skill': 'knife',
           'cost': 2,
           'weight': 20,
           'probability': 'N/A',
           'damage_S': 'd2',
           'damage_L': 'd2',
           'material': 'undefined'},
    1932: {'name': 'crysknife',
           'skill': 'knife',
           'cost': 100,
           'weight': 20,
           'probability': 'N/A',
           'damage_S': 'd10',
           'damage_L': 'd10',
           'material': 'mineral'},
    1933: {'name': 'axe',
           'skill': 'axe',
           'cost': 8,
           'weight': 60,
           'probability': '40',
           'damage_S': 'd6',
           'damage_L': 'd4',
           'material': 'iron'},
    1934: {'name': 'double-headed axe',
           'skill': 'axe',
           'cost': 40,
           'weight': 120,
           'probability': '10',
           'damage_S': 'd8+d4',
           'damage_L': 'd6+2d4',
           'material': 'iron'},
    1935: {'name': 'short sword',
           'skill': 'short sword',
           'cost': 10,
           'weight': 30,
           'probability': '8',
           'damage_S': 'd6',
           'damage_L': 'd8',
           'material': 'iron'},
    1936: {'name': 'runed short sword',
           'skill': 'short sword',
           'cost': 10,
           'weight': 30,
           'probability': '2†',
           'damage_S': 'd8',
           'damage_L': 'd8',
           'material': 'wood'},
    1937: {'name': 'crude short sword',
           'skill': 'short sword',
           'cost': 10,
           'weight': 30,
           'probability': '3†',
           'damage_S': 'd5',
           'damage_L': 'd8',
           'material': 'iron'},
    1938: {'name': 'broad short sword',
           'skill': 'short sword',
           'cost': 10,
           'weight': 30,
           'probability': '2†',
           'damage_S': 'd7',
           'damage_L': 'd8',
           'material': 'iron'},
    1939: {'name': 'curved sword',
           'skill': 'scimitar',
           'cost': 15,
           'weight': 40,
           'probability': '15†',
           'damage_S': 'd8',
           'damage_L': 'd8',
           'material': 'iron'},
    1940: {'name': 'silver saber',
           'skill': 'saber',
           'cost': 75,
           'weight': 40,
           'probability': '6',
           'damage_S': 'd8',
           'damage_L': 'd8',
           'material': 'silver'},
    1941: {'name': 'broadsword',
           'skill': 'broadsword',
           'cost': 10,
           'weight': 70,
           'probability': '8',
           'damage_S': '2d4',
           'damage_L': 'd6+1',
           'material': 'iron'},
    1942: {'name': 'runed broadsword',
           'skill': 'broadsword',
           'cost': 10,
           'weight': 70,
           'probability': '4†',
           'damage_S': 'd6+d4',
           'damage_L': 'd6+1',
           'material': 'wood'},
    1943: {'name': 'long sword',
           'skill': 'long sword',
           'cost': 15,
           'weight': 40,
           'probability': '50†',
           'damage_S': 'd8',
           'damage_L': 'd12',
           'material': 'iron'},
    1944: {'name': 'two-handed sword',
           'skill': 'two-handed sword',
           'cost': 50,
           'weight': 150,
           'probability': '22',
           'damage_S': 'd12',
           'damage_L': '3d6',
           'material': 'iron'},
    1945: {'name': 'samurai sword',
           'skill': 'long sword',
           'cost': 80,
           'weight': 40,
           'probability': '4',
           'damage_S': 'd10',
           'damage_L': 'd12',
           'material': 'iron'},
    1946: {'name': 'long samurai sword',
           'skill': 'two-handed sword',
           'cost': 500,
           'weight': 60,
           'probability': 'N/A',
           'damage_S': 'd16',
           'damage_L': 'd8+2d6',
           'material': 'metal'},
    1947: {'name': 'runed broadsword',
           'skill': 'broadsword',
           'cost': 10,
           'weight': 70,
           'probability': '4†',
           'damage_S': 'd6+d4',
           'damage_L': 'd6+1',
           'material': 'wood'},
    1948: {'name': 'vulgar polearm',
           'skill': 'polearms',
           'cost': 10,
           'weight': 80,
           'probability': '5',
           'damage_S': 'd6',
           'damage_L': 'd6+1',
           'material': 'iron'},
    1949: {'name': 'hilted polearm',
           'skill': 'polearms',
           'cost': 6,
           'weight': 50,
           'probability': '5',
           'damage_S': '2d4',
           'damage_L': '2d4',
           'material': 'iron'},
    1950: {'name': 'forked polearm',
           'skill': 'polearms',
           'cost': 5,
           'weight': 50,
           'probability': '5',
           'damage_S': 'd6+1',
           'damage_L': '2d6',
           'material': 'iron'},
    1951: {'name': 'single-edged polearm',
           'skill': 'polearms',
           'cost': 6,
           'weight': 75,
           'probability': '8',
           'damage_S': 'd6',
           'damage_L': 'd10',
           'material': 'iron'},
    1952: {'name': 'lance',
           'skill': 'lance',
           'cost': 10,
           'weight': 180,
           'probability': '4',
           'damage_S': 'd6',
           'damage_L': 'd8',
           'material': 'iron'},
    1953: {'name': 'angled poleaxe',
           'skill': 'polearms',
           'cost': 10,
           'weight': 150,
           'probability': '8',
           'damage_S': 'd10',
           'damage_L': '2d6',
           'material': 'iron'},
    1954: {'name': 'long poleaxe',
           'skill': 'polearms',
           'cost': 7,
           'weight': 120,
           'probability': '4',
           'damage_S': '2d4',
           'damage_L': '3d4',
           'material': 'iron'},
    1955: {'name': 'pole cleaver',
           'skill': 'polearms',
           'cost': 5,
           'weight': 125,
           'probability': '4',
           'damage_S': '2d4',
           'damage_L': '2d4',
           'material': 'iron'},
    1956: {'name': 'broad pick',
           'skill': 'pick-axe',
           'cost': 50,
           'weight': 120,
           'probability': '13†',
           'damage_S': 'd12',
           'damage_L': 'd8+2d6',
           'material': 'iron'},
    1957: {'name': 'pole sickle',
           'skill': 'polearms',
           'cost': 5,
           'weight': 60,
           'probability': '6',
           'damage_S': 'd6',
           'damage_L': 'd8',
           'material': 'iron'},
    1958: {'name': 'pruning hook',
           'skill': 'polearms',
           'cost': 5,
           'weight': 80,
           'probability': '6',
           'damage_S': '2d4',
           'damage_L': 'd8',
           'material': 'iron'},
    1959: {'name': 'hooked polearm',
           'skill': 'polearms',
           'cost': 7,
           'weight': 120,
           'probability': '4',
           'damage_S': '2d4',
           'damage_L': 'd10',
           'material': 'iron'},
    1960: {'name': 'pronged polearm',
           'skill': 'polearms',
           'cost': 7,
           'weight': 150,
           'probability': '5',
           'damage_S': '2d4',
           'damage_L': 'd6',
           'material': 'iron'},
    1961: {'name': 'beaked polearm',
           'skill': 'polearms',
           'cost': 8,
           'weight': 100,
           'probability': '4',
           'damage_S': 'd8',
           'damage_L': 'd6',
           'material': 'iron'},
    1962: {'name': 'mace',
           'skill': 'mace',
           'cost': 5,
           'weight': 30,
           'probability': '40',
           'damage_S': 'd6+1',
           'damage_L': 'd6',
           'material': 'iron'},
    1963: {'name': 'morning star',
           'skill': 'morning star',
           'cost': 10,
           'weight': 120,
           'probability': '12',
           'damage_S': '2d4',
           'damage_L': 'd6+1',
           'material': 'iron'},
    1964: {'name': 'war hammer',
           'skill': 'hammer',
           'cost': 5,
           'weight': 50,
           'probability': '15',
           'damage_S': 'd4+1',
           'damage_L': 'd4',
           'material': 'iron'},
    1965: {'name': 'club',
           'skill': 'club',
           'cost': 3,
           'weight': 30,
           'probability': '12',
           'damage_S': 'd6',
           'damage_L': 'd3',
           'material': 'wood'},
    1966: {'name': 'rubber hose',
           'skill': 'whip',
           'cost': 3,
           'weight': 20,
           'probability': 'N/A',
           'damage_S': 'd4',
           'damage_L': 'd3',
           'material': 'plastic'},
    1967: {'name': 'staff',
           'skill': 'quarterstaff',
           'cost': 5,
           'weight': 40,
           'probability': '11†',
           'damage_S': 'd6',
           'damage_L': 'd6',
           'material': 'wood'},
    1968: {'name': 'thonged club',
           'skill': 'club',
           'cost': 4,
           'weight': 15,
           'probability': '8',
           'damage_S': 'd6',
           'damage_L': 'd3',
           'material': 'iron'},
    1969: {'name': 'flail',
           'skill': 'flail',
           'cost': 4,
           'weight': 15,
           'probability': '40',
           'damage_S': 'd6+1',
           'damage_L': '2d4',
           'material': 'iron'},
    1970: {'name': 'bullwhip',
           'skill': 'whip',
           'cost': 4,
           'weight': 20,
           'probability': '2',
           'damage_S': 'd2',
           'damage_L': '1',
           'material': 'leather'},
    1971: {'name': 'bow',
           'skill': 'bow',
           'cost': 60,
           'weight': 30,
           'probability': '24',
           'damage_S': 'd2',
           'damage_L': 'd2',
           'material': 'wood'},
    1972: {'name': 'runed bow',
           'skill': 'bow',
           'cost': 60,
           'weight': 30,
           'probability': '12†',
           'damage_S': 'd2',
           'damage_L': 'd2',
           'material': 'wood'},
    1973: {'name': 'crude bow',
           'skill': 'bow',
           'cost': 60,
           'weight': 30,
           'probability': '12†',
           'damage_S': 'd2',
           'damage_L': 'd2',
           'material': 'wood'},
    1974: {'name': 'long bow',
           'skill': 'bow',
           'cost': 60,
           'weight': 30,
           'probability': '0',
           'damage_S': 'd2',
           'damage_L': 'd2',
           'material': 'wood'},
    1975: {'name': 'sling',
           'skill': 'sling',
           'cost': 20,
           'weight': 3,
           'probability': '40',
           'damage_S': 'd2',
           'damage_L': 'd2',
           'material': 'leather'},
    1976: {'name': 'crossbow',
           'skill': 'crossbow',
           'cost': 40,
           'weight': 50,
           'probability': '45†',
           'damage_S': 'd2',
           'damage_L': 'd2',
           'material': 'wood'},
    2348: {'name': 'luckstone',
           'skill': 'sling',
           'cost': 60,
           'weight': 10,
           'damage_S': 'd3',
           'damage_L': 'd3',
           'material': 'mineral'},
    2350: {'name': 'touchstone',
           'skill': 'sling',
           'cost': 45,
           'weight': 10,
           'damage_S': 'd3',
           'damage_L': 'd3',
           'material': 'mineral'},
    2351: {'name': 'flint stone',
           'skill': 'sling',
           'cost': 1,
           'weight': 10,
           'damage_S': 'd6',
           'damage_L': 'd6',
           'material': 'mineral'},
    2352: {'name': 'rock',
           'skill': 'sling',
           'cost': 0,
           'weight': 10,
           'damage_S': 'd3',
           'damage_L': 'd3',
           'material': 'mineral'},
}
